global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'iris-2026'
    metrics_path: '/api/monitor/metrics'
    basic_auth:
      username: '_SYSTEM'
      password: 'SYS'
    static_configs:
      - targets: ['iris-2026:52773']
        labels:
          instance: 'iris-2026'
          version: '2026.1'

  - job_name: 'iris-2025'
    metrics_path: '/api/monitor/metrics'
    basic_auth:
      username: '_SYSTEM'
      password: 'SYS'
    static_configs:
      - targets: ['iris-2025:52773']
        labels:
          instance: 'iris-2025'
          version: '2025.1'
